FROM nvcr.io/nvidia/pytorch:24.03-py3

ENV DEBIAN_FRONTEND noninteractive

##############################################################################
# Pip
##############################################################################
RUN pip install tqdm \
                numpy \
                tiktoken \
                transformers \
                datasets \
                requests

##############################################################################
# cuDNN arm
##############################################################################
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb
RUN apt-get update
RUN apt-get -y install cudnn-cuda-12

RUN git clone https://github.com/NVIDIA/cudnn-frontend.git /root/cudnn-frontend
